doc.type.html
script
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=documentgetelementbyid(header)
src.appendchild(this.img)
filename=covidstrings29gamecode.js
java.awt graphics 
<div id=header></div>
audio=new audio(audio_file mp3)
audio.play 
random button
new button (set random color)
option button
new  button(change color)
public fun with graphics(){
color panel=new j panel();
this add (panel,center)
button panel
new j panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13)))
num teams
total players players per team
if players per team=0
return zero
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string [] args)
jframe f = new covid strings29)
f.set title(covid strings29)
f.set default closeoperation(jframe. exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object= [team color]
covid strings team list29=[black night riders,burgundy rebuilders,red protein spikers,white transit angels ,orange rna messengers,green peacemakers,blue curve crushers,yellow moxie]
covid strings phrase list29=[ non-concatenated strings "covid oral history should not just be limited to new york city"
"bird flu being100 times worse than covid is a reminder that deadly pandemics dont just wait100 years"
"100 years from now people will wonder about how people dealt with covid"
"dont assume that any pandemic follows a100 year cycle" 
"perhaps the bigger point is the idea that people want certainty whenever something like covid happens"
"visually covid will certainly be worse than when it started"
"covid though has changed society even after one year let alone100"
"the next50 years could be filled with coronavirus or non-coronavirus pandemics"
concatenated strings
"the"+"worst"+"pandemic"+"pre-covid"+"would"+"certianly"+"be"+"the"+"spanish"+"flu"
"there"+"have"+"been"+"plenty"+"of"+"plagues"+"pre-covid"+"that"+"have"+"changed"+"history"
"the"+"whos"+"pandemic"+"phase"+"program"+"certainly"+"has"+"covid"+"as"+"a"+"future"+"pandemic"
"this"+"is"+"because"+"it"+"passed"+"all"+"six"+"phases"
"psychic"+"nick"+"aujula"+"was"+"somewhat"+"right"+"about"+"covid"+"ending"+"in"+"2022"
"he"+"also"+"claimed"+"to"+"forsee"+"it"+"in"+"2018"
"unfortunately"+"covid"+"will"+"more"+"likely"+"be"+"an"+"era"+"than"+"a"+"phase"
"even"+"so"+"talking"+"about"+"it"+"is"+"hard"+"even"+"with"+"some"+"oral"+"history"]
covid strings multiple choice list29=[1:a wonder b forget c be on mars d be reading a computer citation,2:a pre b post c during d happening simultaneously,3:a pale rider b oral c digital d30 rock,4:a mapping b talking c doing a post-mortem d turning the page,5:a100 b50 c10 d5,6:a chinese b korean c spanish d kansas,7:a certainty b a scapegoat c revenge d respect,8:a2022 b2023 c3409 d2011,9:a3218 b2018 c2004 d2059,10:a long winters night b era c footnote d blank space,11:a50 b500 c100 d1000,12:a1/16th b1/8th c1 d2,13:a in practice b visually c in theory d definitely]
covid strings29 math problems list=[non- concatenated "if a line of the next50 years showed the number of coronavirus pandemics increased per year what is the relationship"?,"if a line with a slope of 1/32 and a y intercept of16 had5 year intervals what would the y coordinate be if the x coordinate was15 years"?,"if the previous point was reflected across the x axis what are the new coordinates"?,"if the previous point was rotated270 degrees clockwise what is the range"?,"if the previous point was translated16 units down and7 units to the left what is the new point"?,"if the previous point was translated 17/32 units up and17 units to the left what is the new point"?,"if the previous point was translated4units up and20 units to the right what is the new point"?,"if the previous point was translated3units up and1unit to the right, what is the new point"?,
concatenated "if"+"59"+"percent"+"of"+"americans"+"believe"+"that"+"100"+"years"+"from"+"now"+"americas"+"covid"+"response"+"will"+"be"+"viewed"+"as"+"terrible"+"what"+"percent"+"dont"?,"if"+"41"+"percent"+"strongly"+"believe"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"10.18"+"percent"+"what"+"is"+"the"+"range"?,"if"+"68"+"percent"+"agree"+"with"+"the"+"new"+"york"+"times"+"that"+"covid"+"is"+"still"+"confusing"+"after"+"3"+"years"+"what"+"percent"+"dont"?,"if"+"42"+"percent"+"mildy"+"agree"+"what"+"percent"+"is"+"strong"?,"if"+"the"+"margin"+"of"+"error"+"is"+"8.6"+"percent"+"what"+"is"+"the"+"range"?]
covid strings scrambled phrase list29 =["ovicd"+"rea","erciams"+"ovicd"+"storyhi"]
userin.select team
import meta.
class myclass
constructor (non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax
chart js 
def gradient
id=mygradient
gradientunits=userspaceonuse
x1=selected number
y1=16
x2=15
y2= x2*1/32+y1
stop offset=0 stop-color=ff0000
stop offset=1 stop color=0000ff
<lineargradient>
<filter
id=linear1
filterunits=objectboundingbox
x=0%
y=0%
width=100%
height=100%
<fecomponenttransfer>
<fefunccovidstrings  type=linear slope>=1
transformationlist=[reflection,rotation,translation]
if reflection==X Axis:
shift x axis
else:
remain
if rotation==270 degrees clockwise:
shift 270 degrees clockwise
else:
remain
if translation==(-7,-16):
shift 7 units to the left and 16 units down
else:
remain
if translation==(-17,32):
shift 17 units to the left and 32 units up
else:
remain
substring(start,end)
userin.multiple choice
if (s1.length())!=s2.length: 
return false
if s1.length()==s2.length:
return true
char[]arr1=s1.tochararray
char[]arr2= s2.tochararray
arrays.sort(arr1)
arrays.sort(arr2)
if selectedanswer==correct answer:
return true
else:
return false
if selectedanswer=not correct:
return false
else:
return true
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet)
if users team wins covid strings29
console log users team wins covid strings29
else
return game over
return filename
